name: Generate image list

on:
  push:
    paths:
      - "wallpaper/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate images.json
        run: |
          find wallpaper -type f | sed 's|^wallpaper/||' | jq -R . | jq -s . > images.json

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add images.json
          git commit -m "update images" || echo "no change"
          git push